### ISSUE TITLE
Install improvement suggestions

### ISSUE THREAD

**Issue by dylans** [Ninroot/nacre#9]
There are a few issues when trying this out on macOS:

```
$ npm install -g nacre
npm WARN deprecated highlight.js@9.12.0: Version no longer supported. Upgrade to @latest

added 27 packages, and audited 28 packages in 12s

4 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (3 low, 1 moderate)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

The first main issue is reliance on a deprecated package. I know it can be a real pain to keep dependencies current.

Second issue, need to specify a minimum Node.js version. Here's what happens with 14.x:

```
$ nacre
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:readline'
Require stack:
- /usr/local/lib/node_modules/nacre/built/lib/repl.js
- /usr/local/lib/node_modules/nacre/built/index.js
- /usr/local/lib/node_modules/nacre/bin/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nacre/built/lib/repl.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/nacre/built/lib/repl.js',
    '/usr/local/lib/node_modules/nacre/built/index.js',
    '/usr/local/lib/node_modules/nacre/bin/index.js'
  ]
}
```

Also Node 16.x doesn't seem to work with nacre on M1 Macs:

```
$ nvm use 16.13.0
Now using node v16.13.0 (npm v8.1.0)
$ nacre
/usr/local/lib/node_modules/nacre/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen(/usr/local/lib/node_modules/nacre/node_modules/userid/build/Release/userid.node, 0x0001): tried: '/usr/local/lib/node_modules/nacre/node_modules/userid/build/Release/userid.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/usr/local/lib/node_modules/nacre/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/nacre/node_modules/userid/lib/userid.js:4:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

Whereas Node 17.x seems to work fine:

```
default[~]$ nacre
Welcome to Nacre version Beta. Find help at https://nacre.sh.
default>
```

My suggestion:

1. Detect the node version and warn based on a version that's incompatible
2. Update the dependencies

Overall, a fun project!

**Comment by Ninroot** [comment]
Hi @dylans ,

1. the dependency vulnerabilities came from the use of old package `emphasize`. Fix: 751ab83a73f10dbd3e9fa1bd7878e3bcd6bb787a
2. node incompatibility fix (only >=18 is now allowed): ea4f1fb76d9c654535ca287085489cf334c43eb3

Fix has been released today in the nacre 0.4.1: https://www.npmjs.com/package/nacre/v/0.4.1
